# qcs v1.0.4
version: "3.7"

networks:
  qcs_subnet:
    driver: bridge
    ipam:
      config:
        - subnet: "172.20.50.0/24"
          gateway: "172.20.50.1"

volumes:
  qcs-db-data:
  qcs-rdb-data:

services:
  qcs-db:
    container_name: qcs-db
    build:
      context: .
      dockerfile: Dockerfile.database
    networks:
      - qcs_subnet
    ports:
      - "33332:5432"
    environment:
      POSTGRES_USER: quickcerts
      POSTGRES_PASSWORD: password
      POSTGRES_DB: quickcerts
    volumes:
      - qcs-db-data:/var/lib/postgresql/data
    restart: unless-stopped

  qcs-cache:
    container_name: qcs-cache
    build:
      context: .
      dockerfile: Dockerfile.redis
    networks:
      - qcs_subnet
    ports: # You can remove this if you don't need to access redis from outside the container
      - "33334:6379"
    volumes:
      - qcs-rdb-data:/data
    restart: unless-stopped

  qcs-server:
    container_name: qcs-server
    build:
      context: .
      dockerfile: Dockerfile.server
    networks:
      - qcs_subnet
    ports:
      - "33333:33333"
    depends_on:
      - qcs-db
      - qcs-cache
    environment:
      DB_HOST: qcs-db
      DB_PORT: 5432
    restart: unless-stopped
